use std::error::Error;

pub async fn handle() -> Result<(), Box<dyn Error>> {
    Ok(())
}
