use std::error::Error;

pub async fn handle() -> Result<(), Box<dyn Error>> {
    println!("Running test data");

    Ok(())
}
